name = "LearnVanishingIdeal"
uuid = "d5b806d3-2ca9-4def-9329-52b8f0583639"
authors = ["Matthias Himmelmann <matthias.himmelmann@outlook.de>"]
version = "0.1.4"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Combinatorics = "1.0.2"
HomotopyContinuation = "2.5"
julia = "1.4"
